version: '2'

services:
    reverseproxy:
        build: nginx_conf/.
        ports:
            - 8080:8080
            - 8081:8081
            - 8082:8082
        restart: always
        networks:
            - reverse

    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always
        networks:
            - reverse

    apache:
        depends_on:
            - reverseproxy
        image: httpd:alpine
        restart: always
        networks:
            - reverse

    flaskapp:
        depends_on:
            - reverseproxy
        build: app/.
        restart: always
        expose:
            - "80"
        networks:
            - reverse

networks:
    reverse:
